# This is a basic workflow to help you get started with Actions

name: Web deploy

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install, build and test
      run: npm install
      
#    # Yarn install
#    - name: GitHub Action for Yarn
#      uses: Borales/actions-yarn@v2.1.0
#      with:
#        cmd: install
#
#    # Yarn build
#    - name: Yarn build project
#      uses: Borales/actions-yarn@v2.1.0
#      with:
#        cmd: build
        
    - name: configure amplify
      uses: ambientlight/amplify-cli-action@0.2.0
      with:
        amplify_command: configure
        amplify_env: react
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
    
    - name: deploy
      uses: ambientlight/amplify-cli-action@0.2.0
      with:
        amplify_command: publish
        amplify_env: prod
        build_command: 'npm run build'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-12    
   
